version: '3'

services:
  web1:
    build:
      context: .
    ports:
      - "8081:80"
    networks:
      - my_network
    volumes:
      - ./web1:/var/www/html:ro

  web2:
    build:
      context: .
    ports:
      - "8082:80"
    networks:
      - my_network
    volumes:
      - ./web2:/var/www/html:ro

  #nginx:
  #  image: nginx:latest
  #  depends_on:
  #    - web1
  #    - web2
  #  ports:
  #    - "80:80"
  #  networks:
  #    - my_network
  #  volumes:
  #    - ./conf/ip-hash.nginx.conf:/etc/nginx/nginx.conf:ro

  amplify:
    image: nginxinc/amplify-agent:latest
    depends_on:
      - web1
      - web2
    ports:
      - "80:80"
    environment:
      - API_KEY=1916ae02ca347ba487bcd9a35c00d700
    networks:
      - my_network
    volumes:
      - ./conf/ip-hash.nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  my_network:
    driver: bridge